nn.exe: connection.o genome.o node.o player.o population.o randomFun.o
	g++ -o nn.exe connection.o genome.o node.o player.o population.o randomFun.o

connection.o: connection.cpp
	g++ -c connection.cpp

genome.o: genome.cpp
	g++ -c genome.cpp

node.o: node.cpp
	g++ -c node.cpp

player.o : player.cpp
	g++ -c player.cpp

population.o : population.cpp
	g++ -c population.cpp

randomFun.o : randomFun.cpp
	g++ -c randomFun.cpp
